---
deployment:
  tasks:
    # Update DEPLOYPATH with your actual cPanel target directory path (e.g. /home/USERNAME/public_html/)
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R dist/* $DEPLOYPATH
