import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        neutral: {
          950: '#0a0a0a',
          900: '#171717',
          800: '#262626',
          700: '#404040',
          600: '#525252',
          500: '#737373',
          400: '#a3a3a3',
          300: '#d4d4d4',
          200: '#e5e5e5',
          100: '#f5f5f5',
          50: '#fafafa',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'JetBrains Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.neutral.700'),
            '--tw-prose-headings': theme('colors.neutral.900'),
            '--tw-prose-lead': theme('colors.neutral.600'),
            '--tw-prose-links': theme('colors.neutral.900'),
            '--tw-prose-bold': theme('colors.neutral.900'),
            '--tw-prose-counters': theme('colors.neutral.500'),
            '--tw-prose-bullets': theme('colors.neutral.400'),
            '--tw-prose-hr': theme('colors.neutral.200'),
            '--tw-prose-quotes': theme('colors.neutral.800'),
            '--tw-prose-quote-borders': theme('colors.neutral.300'),
            '--tw-prose-captions': theme('colors.neutral.500'),
            '--tw-prose-code': theme('colors.neutral.900'),
            '--tw-prose-pre-code': theme('colors.neutral.200'),
            '--tw-prose-pre-bg': theme('colors.neutral.900'),
            '--tw-prose-th-borders': theme('colors.neutral.300'),
            '--tw-prose-td-borders': theme('colors.neutral.200'),
            '--tw-prose-invert-body': theme('colors.neutral.300'),
            '--tw-prose-invert-headings': theme('colors.neutral.100'),
            '--tw-prose-invert-lead': theme('colors.neutral.400'),
            '--tw-prose-invert-links': theme('colors.neutral.100'),
            '--tw-prose-invert-bold': theme('colors.neutral.100'),
            '--tw-prose-invert-counters': theme('colors.neutral.400'),
            '--tw-prose-invert-bullets': theme('colors.neutral.600'),
            '--tw-prose-invert-hr': theme('colors.neutral.800'),
            '--tw-prose-invert-quotes': theme('colors.neutral.200'),
            '--tw-prose-invert-quote-borders': theme('colors.neutral.700'),
            '--tw-prose-invert-captions': theme('colors.neutral.400'),
            '--tw-prose-invert-code': theme('colors.neutral.100'),
            '--tw-prose-invert-pre-code': theme('colors.neutral.200'),
            '--tw-prose-invert-pre-bg': theme('colors.neutral.950'),
            '--tw-prose-invert-th-borders': theme('colors.neutral.700'),
            '--tw-prose-invert-td-borders': theme('colors.neutral.800'),
          },
        },
      }),
    },
  },
  plugins: [
    typography,
  ],
};
