name: Bug Report
description: Create a report to help fix a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for reporting an issue on this repository.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Navigate to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Browser & OS
      description: e.g. Safari 18 on macOS Sonoma, Chrome 130 on Windows 11
    validations:
      required: false
